# Generated by Django 4.2.6 on 2023-10-28 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0003_tipomanutencao_veiculo_motorista_endereco_manutencao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abastecimentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('litros', models.DecimalField(decimal_places=2, max_digits=5)),
                ('kmatual', models.IntegerField()),
                ('km_anterior', models.IntegerField(null=True)),
                ('mediaVeiculo', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacao.veiculo')),
            ],
        ),
    ]
