# Generated by Django 4.2.6 on 2023-10-28 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0004_abastecimentos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abastecimentos',
            name='km_anterior',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
