# Generated by Django 4.2.6 on 2023-10-29 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0005_alter_abastecimentos_km_anterior'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipomanutencao',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
