# Generated by Django 4.2.6 on 2023-11-10 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0007_alter_tipomanutencao_produto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abastecimentos',
            name='litros',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='abastecimentos',
            name='mediaVeiculo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='tipomanutencao',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
